version: "3"
services: 
  minecraft_server:
    build:
      context: .
    command: bash -c "java -Xmx${MAX_RAM} -Xms${MIN_RAM} -jar server.jar nogui"
    ports:
      - 1000:25565
    environment:
      - MIN_RAM=1G
      - MAX_RAM=2G
    volumes:
      - minecraft_v:/home/mnsrvr
volumes:
  minecraft_v:
    driver: local
