version: "3"
services:
  minecraft_server:
    build:
      context: .
    command: bash -c "java -Xmx${MAX_RAM} -Xms${MIN_RAM} -jar server.jar nogui"
    ports:
      - ${LOCAL_PORT}:25565
    volumes:
      - ./:/home/mnsrvr
